export const modalSRC = {
  11: "https://nyangmeonggood.github.io/mains/fullSlide/",
  12: "https://nyangmeonggood.github.io/mains/sideChange/",
  13: "https://nyangmeonggood.github.io/mains/PicChangedByList/",
  14: "https://nyangmeonggood.github.io/mains/blendBackground/",
  15: "https://nyangmeonggood.github.io/mains/popCorner/",
  16: "https://nyangmeonggood.github.io/mains/bookshelf/",
  21: "https://nyangmeonggood.github.io/mains/ColorBubble/",
  22: "https://nyangmeonggood.github.io/mains/bottomBlur/",
  23: "https://nyangmeonggood.github.io/mains/grider/",
  24: "https://nyangmeonggood.github.io/mains/addParts/",
  25: "https://nyangmeonggood.github.io/mains/switchProduct/",
  26: "https://nyangmeonggood.github.io/mains/loopSlide/",
  31: "https://nyangmeonggood.github.io/mains/verticalSwipe/",
  32: "https://nyangmeonggood.github.io/mains/autoBGandGauge/",
  33: "https://nyangmeonggood.github.io/mains/blind/",
};
