export const Preview = {
  11: {
    name: "Fullpage Slide",
    desc: "Slide & Click motion & Canvas",
    responsive: true,
    pages: true,
    img: "./img/fullSlide.jpg",
  },
  12: {
    name: "DailyMain",
    desc: "Detect Time, location & Use localStorage",
    responsive: true,
    img: "./img/dailyMain.jpg",
  },
  13: {
    name: "B : PicChangedByList",
    desc: "Slide & Click motion",
    responsive: true,
    img: "./img/picChangedByList.jpg",
  },
  14: {
    name: "Blend Background",
    desc: "Page Changing Motion & Canvas Animation",
    responsive: true,
    img: "./img/blendBackground.jpg",
  },
  15: {
    name: "Pop Corner",
    desc: "Page Changing Motion & Pointer Animation",
    responsive: true,
    img: "./img/popCorner.jpg",
  },
  16: {
    name: "UnC : BookShelf",
    desc: "Slide & Pointer Animation",
    responsive: true,
    img: "./img/fullSlide.jpg",
  },
  17: {
    name: "SideHideMenu",
    desc: "Responsive Touch Motion & Swipe on mobile",
    responsive: true,
    img: "./img/sideHideMenu.jpg",
  },
  18: {
    name: "BlockList",
    desc: "Tilt Motion",
    responsive: true,
    img: "./img/blockList.jpg",
  },
  19: {
    name: "EnteringBox",
    desc: "Scroll Interaction",
    responsive: true,
    img: "./img/enteringBox.jpg",
  },
  21: {
    name: "ColorBubble",
    desc: "Canvas Animation",
    responsive: true,
    img: "./img/colorBubble.jpg",
  },
  22: {
    name: "BottomBlur",
    desc: "Slide Animation & Click motion",
    responsive: true,
    img: "./img/bottomBlur.jpg",
  },
  23: {
    name: "Grider",
    desc: "Page Changing Motion & Swipe on mobile",
    responsive: true,
    img: "./img/grider.jpg",
  },
  24: {
    name: "AddParts",
    desc: "Scroll Animation & Scroll Menu",
    responsive: true,
    img: "./img/addParts.jpg",
  },
  25: {
    name: "SwitchProduct",
    desc: "Slide & Swipe on mobile",
    responsive: true,
    img: "./img/switchProduct.jpg",
  },
  26: {
    name: "LoopSlide",
    desc: "Loop Slide & Swipe on mobile",
    responsive: true,
    img: "./img/loopSlide.jpg",
  },
  27: {
    name: "CursorChaser",
    desc: "Type Interaction & Pointer Animation",
    responsive: true,
    img: "./img/cursorChaser.jpg",
  },
  28: {
    name: "BarList",
    desc: "Page Changing Motion",
    responsive: true,
    img: "./img/barList.jpg",
  },
  29: {
    name: "DragBox",
    desc: "Swipe Animation",
    responsive: true,
    img: "./img/dragBox.jpg",
  },
  31: {
    name: "VerticalSwipe",
    desc: "keypad (Up Down) motion<br />& Swipe on max-width 900px",
    responsive: true,
    img: "./img/verticalSwipe.jpg",
  },
  32: {
    name: "AutoBGandGauge",
    desc: "Autochange Slide & Gauge keyframe",
    responsive: true,
    img: "./img/autoBGandGauge.jpg",
  },
  33: {
    name: "Blind",
    desc: "Intro Animation",
    responsive: true,
    img: "./img/blind.jpg",
  },
  34: {
    name: "CircleSlide",
    desc: "Page Changing Motion",
    responsive: true,
    img: "./img/circleSlide.jpg",
  },
  35: {
    name: "TimeLine",
    desc: "Slide & Swipe on mobile",
    responsive: true,
    img: "./img/timeLIne.jpg",
  },
  36: {
    name: "Gallery",
    desc: "List & Modal & Parallex",
    responsive: true,
    img: "./img/gallery.jpg",
  },
  37: {
    name: "ModalInfo",
    desc: "modal",
    responsive: true,
    img: "./img/modalInfo.jpg",
  },
  38: {
    name: "YellowCard",
    desc: "Scroll Interaction",
    responsive: true,
    img: "./img/yellowCard.jpg",
  },
  39: {
    name: "tripAdviser",
    desc: "fullPage",
    responsive: true,
    img: "./img/tripAdviser.jpg",
  },
};
