export const Preview = {
  11: {
    name: "Fullpage Slide",
    desc: "Slide & Click motion & Canvas",
    responsive: true,
    pages: true,
  },
  12: {
    name: "X : SideChange",
    desc: "Hover motion & keypad (← →) motion<br />& Swipe on mobile ",
    responsive: true,
  },
  13: {
    name: "B : PicChangedByList",
    desc: "Slide & Click motion",
    responsive: true,
  },
  14: {
    name: "Blend Background",
    desc: "Page Changing Motion & Canvas Animation",
    responsive: true,
  },
  15: { name: "Pop Corner", desc: "Page Changing Motion & Pointer Animation", responsive: true },
  16: { name: "16", desc: "16src", responsive: true },
  17: { name: "17", desc: "17src", responsive: true },
  18: { name: "18", desc: "18src", responsive: true },
  19: { name: "19", desc: "19src", responsive: true },
  21: { name: "ColorBubble", desc: "Canvas Animation", responsive: true },
  22: {
    name: "BottomBlur",
    desc: "Slide Animation & Click motion",
    responsive: true,
  },
  23: {
    name: "Grider",
    desc: "Page Changing Motion & Swipe on mobile",
    responsive: true,
  },
  24: { name: "24", desc: "24src", responsive: true },
  25: { name: "25", desc: "25src", responsive: true },
  26: { name: "26", desc: "26src", responsive: true },
  27: { name: "27", desc: "27src", responsive: true },
  28: { name: "28", desc: "28src", responsive: true },
  29: { name: "29", desc: "29src", responsive: true },
  31: {
    name: "VerticalSwipe",
    desc: "keypad (↑ ↓) motion<br />& Swipe on max-width 900px",
    responsive: true,
  },
  32: {
    name: "AutoBGandGauge",
    desc: "Autochange Slide & Gauge keyframe",
    responsive: true,
  },
  33: { name: "Blind", desc: "Intro Animation", responsive: true },
  34: { name: "34", desc: "34src", responsive: true },
  35: { name: "35", desc: "35src", responsive: true },
  36: { name: "36", desc: "36src", responsive: true },
  37: { name: "37", desc: "37src", responsive: true },
  38: { name: "38", desc: "38src", responsive: true },
  39: { name: "39", desc: "39src", responsive: true },
};
