export const Preview = {
  11: {
    name: "Fullpage Slide",
    desc: "Slide & Click motion & Canvas",
    responsive: true,
    pages: true,
  },
  12: {
    name: "X : SideChange",
    desc: "Hover motion & keypad (Left Right) motion<br />& Swipe on mobile ",
    responsive: true,
  },
  13: {
    name: "B : PicChangedByList",
    desc: "Slide & Click motion",
    responsive: true,
  },
  14: {
    name: "Blend Background",
    desc: "Page Changing Motion & Canvas Animation",
    responsive: true,
  },
  15: {
    name: "Pop Corner",
    desc: "Page Changing Motion & Pointer Animation",
    responsive: true,
  },
  16: {
    name: "UnC : BookShelf",
    desc: "Slide & Pointer Animation",
    responsive: true,
  },
  17: {
    name: "SideHideMenu",
    desc: "Responsive Touch Motion & Swipe on mobile",
    responsive: true,
  },
  18: { name: "BlockList", desc: "Tilt Motion", responsive: true },
  19: { name: "EnteringBox", desc: "Scroll Interaction", responsive: true },
  21: { name: "ColorBubble", desc: "Canvas Animation", responsive: true },
  22: {
    name: "BottomBlur",
    desc: "Slide Animation & Click motion",
    responsive: true,
  },
  23: {
    name: "Grider",
    desc: "Page Changing Motion & Swipe on mobile",
    responsive: true,
  },
  24: {
    name: "AddParts",
    desc: "Scroll Animation & Scroll Menu",
    responsive: true,
  },
  25: {
    name: "SwitchProduct",
    desc: "Slide & Swipe on mobile",
    responsive: true,
  },
  26: {
    name: "LoopSlide",
    desc: "Loop Slide & Swipe on mobile",
    responsive: true,
  },
  27: { name: "27", desc: "27src", responsive: true },
  28: { name: "28", desc: "28src", responsive: true },
  29: { name: "29", desc: "29src", responsive: true },
  31: {
    name: "VerticalSwipe",
    desc: "keypad (Up Down) motion<br />& Swipe on max-width 900px",
    responsive: true,
  },
  32: {
    name: "AutoBGandGauge",
    desc: "Autochange Slide & Gauge keyframe",
    responsive: true,
  },
  33: { name: "Blind", desc: "Intro Animation", responsive: true },
  34: { name: "CircleSlide", desc: "Page Changing Motion &", responsive: true },
  35: { name: "TimeLine", desc: "Slide & Swipe on mobile", responsive: true },
  36: { name: "Gallery", desc: "List & Modal & Parallex", responsive: true },
  37: { name: "37", desc: "37src", responsive: true },
  38: { name: "38", desc: "38src", responsive: true },
  39: { name: "39", desc: "39src", responsive: true },
};
